[package]
name = "rips-patcher"
version = "0.1.0"
authors = ["dgrubb <davidanthonygrubb@gmail.com>"]
edition = "2018"

[dependencies]
rips_lib = { git = "https://github.com/dgrubb/rips_lib.git" }
clap = "2.33.0"
log = "0.4.8"
simple_logger = "1.0.1"
